# -*- coding: utf-8 -*-
"""test_utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QuRBVQfHHWEXjdz20otI3SdbmL2IY0dI
"""

def rnn_cell_forward_test(rnn_cell_forward):
    raise NotImplementedError


def clip_test(clip):
    raise NotImplementedError


def sample_test(sample):
    raise NotImplementedError


def optimize_test(optimize):
    raise NotImplementedError


def model_test(model):
    raise NotImplementedError